"""add speaking_sessions

Revision ID: 083c2c6e433d
Revises: 67b01ffa4217
Create Date: 2026-07-13 23:44:23.574206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '083c2c6e433d'
down_revision: Union[str, Sequence[str], None] = '67b01ffa4217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaking_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'finished', name='speaking_session_status'), nullable=False),
    sa.Column('turns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaking_sessions')
    # create_table auto-created the enum type, but drop_table does not remove
    # it; drop it explicitly so downgrade -> upgrade round-trips cleanly.
    sa.Enum('active', 'finished', name='speaking_session_status').drop(op.get_bind())
    # ### end Alembic commands ###
